theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

title: DL Docs
description: A DL primer to be used with Jetson 

#baseurl: "/deepnotes"
#url: "https://ganindu7.github.io/deepnotes/"

permalink: pretty 

# exclude: ["topics/tests","topics/images", "*.gemspec", "*.gem"]
exclude: ["topics/tests","topics/images", "*.gemspec", "*.gem"]


ga_tracking_anonymise_ip: true
